version: 2

models:
  - name: dim_conversion_factors
    description: ""
    columns:
      - name: record_key
        description: A surrogate key that uniquely identifies each row
        tests:
          - unique
          - not_null

  - name: fact_energy_consumption
    description: ""
    columns:
      - name: record_key
        description: A surrogate key that uniquely identifies each row
        tests:
          - unique
          - not_null

  - name: mart_greenhouse_gas_emissions
    description: ""
    columns:
      - name: record_key
        description: The surrogate key from `fct_energy_consumption` that uniquely identifies each row
        tests:
          - unique

  