version: 2

sources:

  - name: carbon_emissions_raw
    description: ""
    database: spry-alignment-375710
    schema: carbon_emissions_raw
    loader: Prefect

    tables:

      - name: conversion_factors_raw
        description: ""

      - name: energy_consumption_raw
        description: ""
        