name: 'de_zoomcamp'
version: '1.0.0'
config-version: 2

profile: 'de_zoomcamp'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  de_zoomcamp:
    carbon_emissions:
      +materialized: table

seeds:
  de_zoomcamp:
    +column_types:
      CATEGORY_LEVEL_4: string

